### ISSUE TITLE
AWS S3: Add minimum policy rules for complainer

### ISSUE THREAD

**Issue by andygrunwald** [cloudflare/complainer#18]
I configured complainer with the usage of S3 (`s3aws` from #17). Everything is working fine.
What i asked myself during this road: 
* What Policies / Grants does complainer need to work with S3?
* What are the minimum grants?

I tested it and the only requirement that is needed is:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1465396834000",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::YOUR-BUCKET-NAME/*"
            ]
        }
    ]
}
```

It would make sense to add this to the README / docs for future users.
I didn`t apply a PR (yet), because #17 is not merged yet and this would create a conflict if i put this into the README as well.

**Comment by bobrik** [comment]
Looks like `s3:PutObject` should be enough. Feel free to make a PR to reflect that.

**Comment by andygrunwald** [comment]
See #22
