### ISSUE TITLE
Health endpoint

### ISSUE THREAD

**Issue by andygrunwald** [cloudflare/complainer#26]
Marathon offers you a nice way to define [Health Checks](https://mesosphere.github.io/marathon/docs/health-checks.html). An small and easy interface can be HTTP. As far as i can see such a functionality is not yet implemented in Complainer.

The basic idea is to offer a small http server (by stdlib / net/http) to offer a small `/health` endpoint.
Such a health endpoint should be checking if all dependencies (reporters, uploaders) are available.
In a possible implementation we could extend the [`Reporter`](https://github.com/cloudflare/complainer/blob/master/reporter/reporter.go#L38) and [`Uploader`](https://github.com/cloudflare/complainer/blob/master/uploader/uploader.go#L38) interface and add a new method `Health() error`.

If error is nil, reporter or uploader is healthy. If error != nil, this is not healthy.
With this every reporter / uploader is responsible to check their health on their own.
If no health endpoint / check is possible, a `return nil` might be sufficient.

Questions left:
* What about uploaders / reporters configured by labels / tasks only?

I would love to get your feedback here.

**Comment by bobrik** [comment]
How do you check if things are healthy?

**Comment by andygrunwald** [comment]
This is a good, but tricky question.
For a basic check it is enough if all dependencies of complainer (depends on the configuration, but Slack, S3, Sentry, etc.) are reachable or fulfilled (by their protocol).

E.g.:
* Slack: `HEAD`-Request to https://hooks.slack.com/
* AWS S3: Fire a [`HeadBucket`](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.HeadBucket)-Request

**Comment by bobrik** [comment]
Ok, it's possible to do for static stuff (uploader, mesos itself), but it doesn't looks reasonable for dynamic reporters configured per app. We can probably start with static bits.
