### ISSUE TITLE
Docker-Tag is v1.4, but github release is v1.3

### ISSUE THREAD

**Issue by andygrunwald** [cloudflare/complainer#27]
I saw that the latest github release is v1.3 (https://github.com/cloudflare/complainer/releases/tag/v1.3), but the latest docker hub image is v1.4 (https://hub.docker.com/r/cloudflare/complainer/tags/).

I assume Dockerhub v1.4 == Github Complainer v1.3 ?

**Comment by bobrik** [comment]
My bad, fixed docker hub.
