### ISSUE TITLE
Possibility to set templates per reporter via env vars

### ISSUE THREAD

**Issue by andygrunwald** [cloudflare/complainer#28]
The template functionality is great. Thank you for this feature.
Sadly, this can only be applied by command line argument. See https://github.com/cloudflare/complainer/blob/master/reporter/slack.go#L31
It would be great if we can set a template per reporter via env var as well.

A normal `os.GetEnv` is not enough here, because per reporter there is a default value set.
For this we need a small custom function in complainer like this one: https://github.com/cloudflare/complainer/pull/25/files#diff-405e7bd8f95efdb0e45add9c8a9f8459R63

Would you be open for this PR?

**Comment by bobrik** [comment]
Maybe it's time to have `github.com/cloudflare/complainer/flags` and use it everywhere:

```go

func StringFlag(name, env, fallback, help string) *string {
  value := fallback
  if v := os.Getenv(env); v != "" {
    value = v
  }

  return flag.String(name, value, help)
}
```

https://github.com/cloudflare/complainer/blob/master/uploader/s3common.go

What do you think?

**Comment by andygrunwald** [comment]
This would be a nice one if this is globally available in complainer. This would solve all these issues "this and that is not available by env var" complains (by me, sorry).

The `envOrDefault ` func from #25 would be obsolete by this.

Should i propose the change or will you do it?

**Comment by bobrik** [comment]
Take a look at #29.

**Comment by andygrunwald** [comment]
#29 looks way better than this one. If it will get merged, we can get rid of this one here.
