### ISSUE TITLE
JIRA Reporter

### ISSUE THREAD

**Issue by andygrunwald** [cloudflare/complainer#40]
I think about this quite some time. I want to add a JIRA Reporter.
The implementation to create a JIRA Ticket based on a failing Mesos Task is not a real challenge and i am able to do this.

But there is one doubt that comes into my mind:
Imagine you have a Cronjob that runs every hour (or every 30 minutes, whatever, important is "often). And now it starts failing at 8pm on a friday.
The whole weekend the job is failing and *complainer* is creating tickets for every job run.
My idea is to create only one task per Mesos Job ID / Identifier per Task (not per task run).
With this we can do something like this:
* Job is failing
* JIRA Reporter checks if there is already a ticket for this job which is not resolved, closed, (name the status)
* If there is a ticket that is still not done, skip the error / reporting
* If there is a ticket that with this task id (not run id) and is resolved / closed, create a new jira ticket
* If there is no ticket at all, create one as well

To know if there is already a ticket created, we need a storage (file, S3, in memory, whatever) or we use a kind of "tricky" way to mark a ticket as this and we use JIRA as a "storage".
One idea is to assign tags to a ticket like `complainer, mesos-task-id` and query by them.
In memory won`t be a big deal, but when complainer get rescheduled, your data is gone and ticket will be created twice: Maybe this is acceptable?

The reason for this ticket is not that i want that you start the implementation.
The reason is i want to ask you about your idea about this functionality to avoid a ticket creation flooding. Maybe you have a better idea here?

**Comment by bobrik** [comment]
> If there is a ticket that is still not done, skip the error / reporting

How about "add a comment with the info from the new failure"? This can get pretty messy with constantly failing tasks on Marathon, though.

> To know if there is already a ticket created, we need a storage (file, S3, in memory, whatever) or we use a kind of "tricky" way to mark a ticket as this and we use JIRA as a "storage".

Sentry collapses similar issues by the title. I think it makes sense to do the same with JIRA.

**Comment by andygrunwald** [comment]
> How about "add a comment with the info from the new failure"? This can get pretty messy with constantly failing tasks on Marathon, though.

Good idea. This can be configurable by a label

> Sentry collapses similar issues by the title. I think it makes sense to do the same with JIRA.

Nice idea as well. Can get tricky if the title is templatable. Will think about it.
