### ISSUE TITLE
Eating your own dog food: Complainer should complain about itself

### ISSUE THREAD

**Issue by andygrunwald** [cloudflare/complainer#8]
One idea that comes into my mind: If complainer fails (e.g. due to a node failure), it should complain about itself.

To make this possible we need at minimum two instances of complainer in one cluster. The should be scheduled on different nodes (maybe in different racks).
The challenge is here that these instances need to communicate with each other what instance will handle what failure, otherwise every failure will be reported twice.

One solution can be that a kind of "leader election" or state will be stored in Zookeeper (which is in place already due to the Mesos cluster).

This is just a rough and fast idea. What do you think about it?

**Comment by bobrik** [comment]
No need to store state anywhere, take a look at #10.

**Comment by andygrunwald** [comment]
This is great. Thank you @bobrik!
